[package]
name = "rcomplex"
version = "0.1.0"
authors = ["Eivind Eide <eivind@vikenfiber.no>"]
description = "A simple class for manipulating complex numbers"
license = "MIT/Apache-2.0"
[dependencies]
